  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.1.55:8554/unicast
    name: Living Room

  - platform: generic
    still_image_url: http://192.168.1.55/cgi-bin/currentpic.cgi
    name: Living Room Snap