  - platform: google_maps
    username: !secret gmailuser
    password: !secret gmailpass
  - platform: mqtt
    devices:
      graham_pixel: 'graham_pixel/location'
      bora_s8: 'bora_s8/location'