  use_include_order: True
  include:
    entities:
      - sensor.studymotion_state
      - sensor.kitchenmotion_state
      - sensor.livingroommotion_state
      - sensor.bedroomdoor_state
      - sensor.graham_geocode
      - sensor.bora_geocode
      - light.bedroom
      - light.living_room
      - light.dining_room
      - light.study
      - light.living_room
      - light.dining_room
      - light.study
      - switch.plug_kettle_switch
      - switch.plug_bedroomheater_switch
      - switch.plug_studyheater_switch