  - platform: broadlink
    host: 192.168.1.12
    mac: '78:0F:77:00:D5:7C'
    type: rm
    friendly_name: broadlink
    switches:
      tv:
        friendly_name: "LG TV"
        command_on: 'JgAyAW49DQ8OKw0QDRANDw4PDRANDw4PDQ8ODw0QDQ8OLAsRDg8NDw0QDBENDw4PDRAMEA0tDBANEAwQDRAMEQwQDRANEA0sDBEMLQwtDC0NLQwQDRAMLQwRDC0MLQ0tDC0MEA0tDAAJnG88DBANLQwQDRAMEQwQDRAMEA0QDBEMEA0QDBEMLQwQDRAMEQwQDRAMEQwQDRAMEQwtDBANEAwRDBANEAwRDBANEAwtDBEMLQwtDC4MLQwRDBAMLQ0QDC0NLQwtDC0MEQwtDAAJnG87DREMLQwRDBANEAwQDRAMEQwQDRAMEQwQDRAMLQwRDBANEAwRDBANEAwRDBANEAwtDBEMEA0QDBEMEA0QDBEMEA0sDRAMLQ0tDC0MLQ0QDBANLQwQDS0MLQwtDC0NEAwtDQANBQAAAAAAAA=='
        command_off: 'JgAyAW49DQ8OKw0QDRANDw4PDRANDw4PDQ8ODw0QDQ8OLAsRDg8NDw0QDBENDw4PDRAMEA0tDBANEAwQDRAMEQwQDRANEA0sDBEMLQwtDC0NLQwQDRAMLQwRDC0MLQ0tDC0MEA0tDAAJnG88DBANLQwQDRAMEQwQDRAMEA0QDBEMEA0QDBEMLQwQDRAMEQwQDRAMEQwQDRAMEQwtDBANEAwRDBANEAwRDBANEAwtDBEMLQwtDC4MLQwRDBAMLQ0QDC0NLQwtDC0MEQwtDAAJnG87DREMLQwRDBANEAwQDRAMEQwQDRAMEQwQDRAMLQwRDBANEAwRDBANEAwRDBANEAwtDBEMEA0QDBEMEA0QDBEMEA0sDRAMLQ0tDC0MLQ0QDBANLQwQDS0MLQwtDC0NEAwtDQANBQAAAAAAAA=='

      yamaha_audio:
        friendly_name: "Yamaha Audio Receiver"
        command_on: 'JgBQAAABJpURExM3EhMSOBI4EjcTOBISEzcSExI4EhMSExITEhITOBI3EzcSOBI4EjcTExITEhITEhMTERMTEhMSEjgTNhM4EgAFHwABJ0oSAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABJpURExM3EhMSOBI4EjcTOBISEzcSExI4EhMSExITEhITOBI3EzcSOBI4EjcTExITEhITEhMTERMTEhMSEjgTNhM4EgAFHwABJ0oSAA0FAAAAAAAAAAA='
      av_volume_down:
        friendly_name: "AV Volume -"
        command_on: 'JgBIAAABJ5QSExM3EhMSNxM4EjcTNxITEzcSExM2ExMSExISExITNhQ3EjgSExI4EjcTEhMTERMTEhMSEjgTEhITEjgSNxM3EwANBQ=='
      av_volume_up:
        friendly_name: "AV Volume +"
        command_on: 'JgBIAAABKJMTExI3ExMROBM3EjgSOBITEjcTExE4ExISExITExISOBITEjcTExE4EzcSExMSEhMSOBISEzgSEhMSEzcSOBI4EgANBQ=='
      av_video:
        friendly_name: "AV Video"
        command_on: 'JgBQAAABJpURExM3EhMSOBI4EjcTOBISEzgRExI4EhMSExITEhMSOBI3EzcSOBITEjgSExITEhMSEhMTEhMROBMSEjgSOBI4EgAFHwABJksSAA0FAAAAAAAAAAA='

      fan_power:
        friendly_name: "Fan Power"
        command_on: 'JgBiACYRJhALLCYRJhALLAwrCysMKwsrCywm6CYQJhELLCYQJhELKwwrDCsKLAwrCywm5yYRJhEKLCYRJhALKg0sCiwLLAsrCywm6CYQJxALLCYQJhELLAosCywLKwssCywmAA0FAAAAAAAA'
        command_off: 'JgBiACYRJhALLCYRJhALLAwrCysMKwsrCywm6CYQJhELLCYQJhELKwwrDCsKLAwrCywm5yYRJhEKLCYRJhALKg0sCiwLLAsrCywm6CYQJxALLCYQJhELLAosCywLKwssCywmAA0FAAAAAAAA'
        # command_on: 'AysLFgMrCxY6noEFcBH4dAAAAAAAAAAAAAAAAA=='
        # command_ff: 'AysLFgMrCxY6noEFcBH4dAAAAAAAAAAAAAAAAA=='
      fan_speed:
        friendly_name: "Fan Speed"
        command_on: 'JgBOACYQJhELLCYQJhELKwwrCywKKg0sJw8LAAEBKBEmEAssJhEmEAssCywLKwwrDSkoDw0AAQEmECYRDSomECYRCysNKA8oDCwNKigPDAANBQAAAAAAAAAAAAA='
      fan_mode:
        friendly_name: "Fan Mode"
        command_on: 'JgBOACYRJhELKyYRJhALLAwrCiwLLCYRCysMAAECJhEmEAssJhEnDwssCywLKwwrJhALLAsAAQMmECcQCywmECYRCysMKwssCywmEAssCwANBQAAAAAAAAAAAAA='
      fan_timer:
        friendly_name: "Fan Timer"
        command_on: 'JgBOACgPKA4NKigPKA4NKgssCiwoDwsrCywMAAECKA4mEQ0qKA4oDw0qDCoMKygODSkMLAoAAQMoDyYRDCooDyYRDCoLLA0pKA8LLAwqDQANBQAAAAAAAAAAAAA='
      fan_osc:
        friendly_name: "Fan Oscillate"
        command_on: 'JgBOACgOKA8NKigOKA8NKgwqKA8NKQ0qDCsMAAECJw8mEQwqJhEmEQwqDSooDwwqCywMKwwAAQEoDygPCiwoDygODSoNKiYQDSoMKg0qDQANBQAAAAAAAAAAAAA='