homeassistant:
  name: Molly's House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Australia/Sydney
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
  whitelist_external_dirs:
    - /config/tmp
  customize: !include includes/customize.yaml
  customize_glob: !include customize_glob.yaml

http:
ffmpeg:
map:
config:
sun:
system_health:
stream:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml

# INCLUDES
automation: !include includes/automations.yaml
binary_sensor: !include includes/binary_sensors.yaml
camera: !include includes/camera.yaml
cast: !include includes/cast.yaml
circadian_lighting: !include includes/circadian.yaml
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
discovery: !include includes/discovery.yaml
frontend: !include includes/frontend.yaml
group: !include includes/groups.yaml
habitica: !include includes/habitica.yaml
history: !include includes/history.yaml
hue: !include includes/hue.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
light: !include includes/light.yaml
logbook: !include includes/logbook.yaml
logger: !include includes/logger.yaml
mqtt: !include includes/mqtt.yaml
notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
speedtestdotnet: !include includes/speedtest.yaml
switch: !include includes/switch.yaml
telegram_bot: !include includes/telegram_bot.yaml
tts: !include includes/tts.yaml
yeelight: !include includes/yeelight.yaml
zone: !include includes/zones.yaml