homeassistant:
  name: Molly's House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Australia/Sydney
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

  customize: !include includes/customize.yaml
  customize_glob: !include customize_glob.yaml

http:

light:
  - platform: yeelight
    devices:
      192.168.1.12:
        name: Dining Room Yeelight 1
      192.168.1.13:
        name: Dining Room Yeelight 2

  - platform: group
    name: Dining Room
    entities:
      - light.dining_room_yeelight_1
      - light.dining_room_yeelight_2

# Floor plan
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret graham_telegram_id
      - !secret bora_telegram_id

# Habitica
habitica:
  - api_user: !secret habitica_user
    api_key: !secret habitica_api

# INCLUDES
automation: !include includes/automations.yaml
group: !include includes/groups.yaml
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensors.yaml
camera: !include includes/camera.yaml
cast: !include includes/cast.yaml
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
history: !include includes/history.yaml
logbook: !include includes/logbook.yaml
mqtt: !include includes/mqtt.yaml
notify: !include includes/notify.yaml
switch: !include includes/switch.yaml
zone: !include includes/zones.yaml

logger:
  default: warn

recorder:
  purge_keep_days: 3
  exclude:
    entities:
      - sensor.date

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

  themes: !include_dir_merge_named themes/

hue:
  bridges:
    - host: 192.168.1.120
      allow_unreachable: true

tts:
  - platform: google
    cache: false

ffmpeg:
map:
config:
sun:
system_health:
stream:
discovery:
  ignore:
    - netgear_router

circadian_lighting:
  min_colortemp: 1700
  max_colortemp: 6500
  interval: 600
  transition: 30