# switch.0x00158d00024d8cc9_switch = receiver
# switch.0x00158d00024a7ccd_switch = kettle
# switch.0x00158d0002495404_switch = bedroom heater

########################################################################################################################
#                                                    SENSOR LIGHTS                                                     #
########################################################################################################################

# Light on, dining room (motion detected)
- alias: Light on, dining room (motion detected)
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.dining_room
        state: 'off'
      - condition: time
        after: '06:00:00'
      - condition: time
        before: '22:30:00'
  action:
  - service: light.turn_on
    entity_id: light.dining_room
    data:
      brightness_pct: 100
      color_temp: 153

# Light on, dining room (motion detected), night light
- alias: Light on, dining room (motion detected), night light
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.dining_room
        state: 'off'
      - condition: time
        after: '22:30:00'
      - condition: time
        before: '06:00:00'
  action:
  - service: light.turn_on
    entity_id: light.dining_room
    data:
      brightness_pct: 80
      color_temp: 400

# Light off, dining room (no motion)
- alias: Light off, dining room (no motion)
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.dining_room
      state: 'on'
    - condition: state
      entity_id: sensor.steam_game_graham
      state: ''
    - condition: state
      entity_id: sensor.steam_game_calmdown
      state: ''
  action:
    - service: light.turn_off
      entity_id: light.dining_room

# Light on: kitchen (motion detected)
- alias: Light on, kitchen (motion detected)
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ (state_attr('sun.sun', 'elevation')) < 12 }}"
      - condition: time
        after: '06:00:00'
      - condition: time
        before: '22:00:00'
      - condition: state
        entity_id: light.kitchen
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness_pct: 100
        color_temp: 154

# Light on: kitchen night light
- alias: Light on, kitchen night light
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: light.kitchen
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness_pct: 30
        color_temp: 500

# Light off, kitchen (no motion)
- alias: Light off, kitchen (no motion)
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  condition:
      condition: state
      entity_id: light.kitchen
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.kitchen

# Light on: living room (motion detected)
- alias: Light on, living room (motion detected)
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_living_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '06:00'
    - condition: time
      before: '23:00'
    - condition: template
      value_template: "{{ (state_attr('sun.sun', 'elevation')) < 12 }}"
    - condition: state
      entity_id: light.living_room
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness_pct: 100
        color_temp: 153

# Light on: living room night light
- alias: Light on, living room night light
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_living_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness_pct: 30
        color_temp: 500

# Light off, living room (no motion)
- alias: Light off, living room (no motion)
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_living_occupancy
    from: 'on'
    to: 'off'
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.door_bedroom
          state: 'on'
        - condition: state
          entity_id: light.bedroom
          state: 'off'
        - condition: template
          value_template: "{{ not is_state('media_player.molly_dongle', 'playing') }}"
        - condition: state
          entity_id: light.living_room
          state: 'on'
        - condition: time
          after: "22:30:00"
        - condition: time
          before: "06:00:00"
  action:
    - service: light.turn_off
      entity_id: light.living_room

########################################################################################################################
#                                                           XIAOMI                                                     #
########################################################################################################################


- alias: 'Door open: bedroom light on (daytime)'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_bedroom
    from: 'off'
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness_pct: 100
        color_temp: 153

- alias: 'Door closed: bedroom light off'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_bedroom
    from: 'on'
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.bedroom

- alias: 'Bedroom button: light on (daytime)'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/button_bedroom'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.bedroom
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness_pct: 100
        color_temp: 153

- alias: 'Bedroom button: light offs off'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/button_bedroom'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.bedroom
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.bedroom
    - service: light.turn_off
      entity_id: light.living_room
    - service: light.turn_off
      entity_id: light.kitchen
    - service: light.turn_off
      entity_id: light.dining
    - service: light.turn_off
      entity_id: light.study

- alias: 'Bedroom switch: light on'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_bedroom'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.bedroom
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness_pct: 100
        color_temp: 153

- alias: 'Bedroom switch: light off'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_bedroom'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.bedroom
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bedroom

- alias: 'Kitchen switch: light on'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_kitchen'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.kitchen
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness_pct: 100
        color_temp: 153

- alias: 'Kitchen switch: light off'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_kitchen'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.kitchen
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.kitchen

- alias: 'Study switch: light on'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_study'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.study
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.study
        brightness_pct: 100
        color_temp: 153

- alias: 'Study switch: light off (daytime)'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_study'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
      - condition: state
        entity_id: light.study
        state: 'on'
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
  action:
    - service: light.turn_off
      entity_id: light.study

- alias: 'Study switch: light off (night)'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_study'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00:00'
        before: '07:00:00'
      - condition: state
        entity_id: light.study
        state: 'on'
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click }}"
  action:
    - service: light.turn_off
      entity_id: light.study
    - service: light.turn_on
      entity_id: light.living_room

- alias: 'Left switch: living room on'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_living'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'left' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.living_room
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness_pct: 100
        color_temp: 153

- alias: 'Left switch: living room off'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_living'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'left' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.living_room
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.living_room

- alias: 'Right switch: dining room on'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_living'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'right' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.dining_room
        state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.dining_room
      brightness_pct: 100
      color_temp: 153

- alias: 'Right switch: dining room off'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_living'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'right' == trigger.payload_json.click }}"
      - condition: state
        entity_id: light.dining_room
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.dining_room

- alias: 'Both switches: living/dining room toggle'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/wall_living'
  condition:
    condition: template
    value_template: "{{ 'both' == trigger.payload_json.click }}"
  action:
    service: light.toggle
    entity_id: light.living_room, light.dining_room
