# HA Uptime
- platform: uptime
  name: "HA uptime"
  unit_of_measurement: minutes

- platform: aftership
  api_key: !secret aftership_key

# Fitbit
- platform: fitbit
  clock_format: 24H
  unit_system: metric
  monitored_resources:
    - "activities/calories"
    - "activities/caloriesBMR"
    - "activities/distance"
    - "activities/elevation"
    - "activities/floors"
    - "activities/heart"
    - "activities/minutesFairlyActive"
    - "activities/minutesLightlyActive"
    - "activities/minutesSedentary"
    - "activities/minutesVeryActive"
    - "activities/steps"
    - "activities/activityCalories"
    - "body/fat"
    - "body/bmi"
    - "body/weight"
    - "devices/battery"
    - "sleep/awakeningsCount"
    - "sleep/efficiency"
    - "sleep/minutesAfterWakeup"
    - "sleep/minutesAsleep"
    - "sleep/minutesAwake"
    - "sleep/minutesToFallAsleep"
    - "sleep/startTime"
    - "sleep/timeInBed"

# Google Geocode
- platform: google_geocode
  name: graham_geocode
  origin: device_tracker.google_maps_116993081434204761650
  options: street_number, street, city
  api_key: !secret places_api

- platform: google_geocode
  name: bora_geocode
  origin: device_tracker.google_maps_111604514484536138497
  options: street_number, street,city
  api_key: !secret places_api

- platform: transport_nsw
  name: 'Next train to Central'
  stop_id: '2114181'
  api_key: !secret 'transportnswkey'

# Weather
- platform: darksky
  api_key: !secret darksky_key
  language: it
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
  scan_interval:
    minutes: 5

# Transit
- platform: google_travel_time
  name: Drive to ATA
  api_key: !secret google_api
  origin: zone.home
  destination: 1 Fitzwilliam St, Parramatta
  options:
    mode: driving

- platform: google_travel_time
  name: Drive to Aje
  api_key: !secret google_api
  origin: zone.home
  destination: 94 Oxford St, Paddington
  options:
    mode: driving

# - platform: transport_nsw
#   name: 'Next train to Central'
#   stop_id: '2114181'
#   api_key: !secret 'transportnswkey'

# System Monitor
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: enp7s0
  - type: network_out
    arg: enp7s0
  - type: last_boot

# Pihole
- platform: pi_hole
  host: 192.168.1.6
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - queries_cached
    - queries_forwarded
    - unique_clients
    - unique_domains

########################################################################################################################
#                                                 TEMPLATE SENSORS                                                     #
########################################################################################################################

- platform: template
  sensors: 

    circadian_rounded:
      value_template: "{{ (states('sensor.circadian_values') | round(2)) }}"
      friendly_name: 'Circadian Value'
    habitica_droidonomy_health:
      value_template: "{{ ( states('sensor.habitica_droidonomy_hp') | round(0)) }}"
      friendly_name: 'Health'
      unit_of_measurement: HP
    habitica_droidonomy_gold:
      value_template: "{{ ( states('sensor.habitica_droidonomy_gp') | round(0)) }}"
      friendly_name: 'Gold'
      unit_of_measurement: Gold

# Aftership
    aftership_pending:
      value_template: '{{ states.sensor.aftership.attributes.pending }}'
      friendly_name: 'Pending'
    aftership_intransit:
      value_template: '{{ states.sensor.aftership.attributes.intransit }}'  
      friendly_name: 'In Transit'
    aftership_delivered:
      value_template: '{{ states.sensor.aftership.attributes.delivered }}'  
      friendly_name: 'Delivered'

# Sun
    time_sunrise:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
    time_sunset:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
    time_next_dawn:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_dawn) | timestamp_custom("%H:%M") }}'
    time_next_dusk:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_dusk) | timestamp_custom("%H:%M") }}'
    time_sun_elevation:
      value_template: '{{ states.sun.sun.attributes.elevation }}'
    time_sun_azimuth:
      value_template: '{{ states.sun.sun.attributes.azimuth }}'

    bora_geocode_trunc:
      value_template: "{{ states.sensor.bora_geocode.state|replace(', Sydney', '')}}"

    graham_battery:
      value_template: '{{ states.device_tracker.google_maps_116993081434204761650.attributes.battery_level }}'  
      friendly_name: 'Graham Pixel 3 Battery' 
      unit_of_measurement: '%'
      icon_template: >
       {% set battery_level = states.device_tracker.google_maps_116993081434204761650.attributes.battery_level|default(0)|int %}
       {% set battery_round = (battery_level / 10) |int * 10 %}
       {% if battery_round >= 100 %}
         mdi:battery
        {% elif battery_round > 0 %}
         mdi:battery-{{ battery_round }}
       {% else %}
         mdi:battery-alert
       {% endif %}

    bora_battery:
      value_template: '{{ states.device_tracker.google_maps_111604514484536138497.attributes.battery_level }}'  
      friendly_name: 'Bora Galaxy S8 Battery' 
      unit_of_measurement: '%'
      icon_template: >
       {% set battery_level = states.device_tracker.google_maps_111604514484536138497.attributes.battery_level|default(0)|int %}
       {% set battery_round = (battery_level / 10) |int * 10 %}
       {% if battery_round >= 100 %}
         mdi:battery
        {% elif battery_round > 0 %}
         mdi:battery-{{ battery_round }}
       {% else %}
         mdi:battery-alert
       {% endif %}

# Template for Floorplan
    bedroom_door_closed:
      entity_id: binary_sensor.door_bedroom
      value_template: >
        {% if is_state('binary_sensor.door_bedroom', 'off') %}
          on
        {% else %}
          off
        {% endif %}

    study_motion:
      entity_id: binary_sensor.motion_study
      value_template: >
        {% if is_state('binary_sensor.motion_study_occupancy', 'on') %}
          on
        {% else %}
          off
        {% endif %}

    kitchen_motion:
      entity_id: binary_sensor.motion_kitchen
      value_template: >
        {% if is_state('binary_sensor.motion_kitchen', 'on') %}
          on
        {% else %}
          off
        {% endif %}

    livingroom_motion:
      entity_id: binary_sensor.motion_living
      value_template: >
        {% if is_state('binary_sensor.motion_living', 'on') %}
          on
        {% else %}
          off
        {% endif %}

- platform: mqtt
  state_topic: 'monitor/ha-monitor/3c:28:6d:2b:f1:cd'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Graham Pixel Bluetooth'

- platform: mqtt
  state_topic: 'monitor/ha-monitor/c8:d7:b0:ad:51:1f'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Bora S8 Bluetooth'