- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/poebae.duckdns.org/cert.pem | awk '{ print $NF }'"


# HA Uptime
- platform: uptime
  name: "HA uptime"
  unit_of_measurement: minutes

# Weather
- platform: darksky
  api_key: !secret darksky_key
  language: it
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
  scan_interval:
    minutes: 5

# Transit
- platform: google_travel_time
  name: Drive to ATA
  api_key: !secret google_api
  origin: zone.home
  destination: 1 Fitzwilliam St, Parramatta
  options:
    mode: driving

# System Monitor
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: enp7s0
  - type: network_out
    arg: enp7s0
  - type: last_boot

# Pihole
- platform: pi_hole
  host: 192.168.1.69
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - queries_cached
    - queries_forwarded
    - unique_clients
    - unique_domains

# Steam
# Suntory    - 76561198268190094
- platform: steam_online
  api_key: !secret steamkey
  accounts:
    - 76561198051415178
    - 76561198302985542
    - 76561198053059377
    - 76561198017280281
    - 76561197982549749
    - 76561198078583977

- platform: template
  sensors:
    graham_suburb:
      friendly_name: "Graham Suburb"
      value_template: "{{ states.sensor.pixel_3_geocoded_location.attributes.Locality }}"

- platform: template
  sensors:
    graham_road:
      friendly_name: "Graham Road"
      value_template: "{{ states.sensor.pixel_3_geocoded_location.attributes.Thoroughfare }}"

- platform: template
  sensors:
    bora_suburb:
      friendly_name: "Bora Suburb"
      value_template: "{{ states.sensor.bora_geocoded_location.attributes.Locality }}"

- platform: template
  sensors:
    bora_road:
      friendly_name: "Bora Road"
      value_template: "{{ states.sensor.bora_geocoded_location.attributes.Thoroughfare }}"

# Current Steam game  
- platform: template
  sensors:
    steam_game_calmdown:
      friendly_name: "Game"
      value_template: "{{ states.sensor.steam_76561198302985542.attributes.game }}"

- platform: template
  sensors:
    steam_game_jono:
      friendly_name: "Game"
      value_template: "{{ states.sensor.steam_76561197982549749.attributes.game }}"

- platform: template
  sensors:
    steam_game_mike:
      friendly_name: "Game"
      value_template: "{{ states.sensor.steam_76561198017280281.attributes.game }}"

- platform: template
  sensors:
    steam_game_graham:
      friendly_name: "Game"
      value_template: "{{ states.sensor.steam_76561198051415178.attributes.game }}"

- platform: template
  sensors:
    steam_game_ww:
      friendly_name: "Game"
      value_template: "{{ states.sensor.steam_76561198053059377.attributes.game }}"

- platform: template
  sensors:
    steam_game_willy:
      friendly_name: "Game"
      value_template: "{{ states.sensor.steam_76561198078583977.attributes.game }}"

# In game?
- platform: template
  sensors:
    ingame:
      friendly_name: "In Game?"
      value_template: >-
        {% if is_state('sensor.steam_game_calmdown', '') %}
          no
        {% endif %}

########################################################################################################################
#                                                 TEMPLATE SENSORS                                                     #
########################################################################################################################

# Sun
    time_sunrise:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
    time_sunset:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
    time_next_dawn:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_dawn) | timestamp_custom("%H:%M") }}'
    time_next_dusk:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_dusk) | timestamp_custom("%H:%M") }}'
    time_sun_elevation:
      value_template: '{{ states.sun.sun.attributes.elevation }}'
    time_sun_azimuth:
      value_template: '{{ states.sun.sun.attributes.azimuth }}'
